// Generated by https://quicktype.io

export interface PurchaseOrder {
  customer:          string;
  deliveryAddress:   string;
  deliveryDate:      string;
  deliveryState:     string;
  files:             Files;
  firm:              string;
  issueDate:         string;
  itemPrice:         ItemPrice[];
  items:             Item[];
  marketingEmployee: string;
  number:            number;
  poNumber:          number;
  remarks:           string;
  warrentyEarly:     boolean;
  status:            string;
}

export interface Files {
  customerDocuments:  CustomerDocument[];
  technicalDocuments: any[];
}

export interface CustomerDocument {
  name: string;
  path: string;
}

export interface ItemPrice {
  description:  string;
  gst:          number;
  qty:          number;
  totalPrice:   number;
  totalWithGst: number;
  unitPrice:    number;
}

export interface Item {
  classHv:      string;
  classLv:      string;
  description:  string;
  qty:          number;
  rating:       number;
  remark:       string;
  standard:     string;
  tapVariation: string;
  terminalHv:   string;
  terminalLv:   string;
  type:         string;
  descrition?:  string;
}
